### ISSUE TITLE
AttributeError: module 'rules' has no attribute 'create_ruleset'`

### ISSUE THREAD

**Issue by Acring** [jruizgit/rules#118]
1. Ubuntu 16.04
2. python 3.5
3. test.py

`from durable.lang import *
with ruleset('test'):
    @when_all(m.subject == 'World')
    def say_hello(c):
        print ('Hello {0}'.format(c.m.subject))

    @when_start
    def start(host):
        host.post('test', { 'subject': 'World' })

run_all()`

`Traceback (most recent call last):
  File "/home/acring/code/python/test/test.py", line 11, in <module>
    run_all()
  File "/usr/local/lib/python3.5/dist-packages/durable/lang.py", line 671, in run_all
    main_host = create_host(databases, state_cache_size)
  File "/usr/local/lib/python3.5/dist-packages/durable/lang.py", line 663, in create_host
    main_host = engine.Host(ruleset_definitions, databases, state_cache_size)
  File "/usr/local/lib/python3.5/dist-packages/durable/engine.py", line 947, in __init__
    self.register_rulesets(None, ruleset_definitions)
  File "/usr/local/lib/python3.5/dist-packages/durable/engine.py", line 1022, in register_rulesets
    rulesets = Ruleset.create_rulesets(parent_name, self, ruleset_definitions, self._state_cache_size)
  File "/usr/local/lib/python3.5/dist-packages/durable/engine.py", line 542, in create_rulesets
    branches[name] = Ruleset(name, host, definition, state_cache_size)
  File "/usr/local/lib/python3.5/dist-packages/durable/engine.py", line 413, in __init__
    self._handle = rules.create_ruleset(state_cache_size, name, json.dumps(ruleset_definition, ensure_ascii=False))
AttributeError: module 'rules' has no attribute 'create_ruleset'`

I am so confounded.

**Comment by Acring** [comment]
and when i run the same code in Window, Python 3.6, i get `Process finished with exit code -1073741819 (0xC0000005)`

**Comment by jruizgit** [comment]
Hi, thanks for reporting the problem. It seems the 'durable_rules' module did not install correctly. The 'rules' native extension will be built when doing `pip install`. 

You need to install VC++ 14 (see https://wiki.python.org/moin/WindowsCompilers). Using a C++ terminal (the shortcuts are installed by the VC++ installer), you can do `pip install durable_rules`. Please make sure you use the 64 bit terminal if you installed Python 64 bit build.

**Comment by jruizgit** [comment]
One more question, for the case of Ubuntu, what was the output when doing pip install?

**Comment by amthenia** [comment]
I also have problems installing it. I would love some instructions to install it for python 2 + 3.
Cool Project!

**Comment by Balakumarkct** [comment]
Below is the issue when trying to install in Cygwin:
 BALA@BALA-PC ~/pyhton_learning/firstapp
$ pip install durable_rules
Collecting durable_rules
  Using cached https://files.pythonhosted.org/packages/c1/2a/8082c70e46afbda0b76da260403de4302a14772557301e959e635c70ffef/durable_rules-2.0.7.tar.gz
Installing collected packages: durable-rules
  Running setup.py install for durable-rules ... done
Successfully installed durable-rules-2.0.7

BALA@BALA-PC ~/pyhton_learning/firstapp
$ python test.py
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    post('test', { 'subject': 'World' })
  File "/home/BALA/pyhton_learning/firstapp/durable/lang.py", line 666, in post
    return get_host().post(ruleset_name, message, complete)
  File "/home/BALA/pyhton_learning/firstapp/durable/lang.py", line 661, in get_host
    _main_host.register_rulesets(ruleset_definitions)
  File "/home/BALA/pyhton_learning/firstapp/durable/engine.py", line 783, in register_rulesets
    rulesets = Ruleset.create_rulesets(self, ruleset_definitions)
  File "/home/BALA/pyhton_learning/firstapp/durable/engine.py", line 389, in create_rulesets
    branches[name] = Ruleset(name, host, definition)
  File "/home/BALA/pyhton_learning/firstapp/durable/engine.py", line 312, in __init__
    self._handle = rules.create_ruleset(name, json.dumps(ruleset_definition, ensure_ascii=False))
AttributeError: 'module' object has no attribute 'create_ruleset'

**Comment by Irazall** [comment]
Same here! First I install the package:
>  (virtual-env) irazall@irazall-yoga:~/promotion/it/python-projects/reporting-errors$ pip install durable-rules
Collecting durable-rules
  Using cached https://files.pythonhosted.org/packages/c1/2a/8082c70e46afbda0b76da260403de4302a14772557301e959e635c70ffef/durable_rules-2.0.7.tar.gz
Installing collected packages: durable-rules
  Running setup.py install for durable-rules ... done
Successfully installed durable-rules-2.0.7

And after executing the "hello world"-snippet, I get the same error message as everyone else:

> Traceback (most recent call last):
  File "/home/irazall/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.5728.98.plugins/python/helpers/pydev/pydevd.py", line 2060, in <module>
    main()
  File "/home/irazall/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.5728.98.plugins/python/helpers/pydev/pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/irazall/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.5728.98.plugins/python/helpers/pydev/pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/irazall/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.5728.98.plugins/python/helpers/pydev/pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/irazall/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.5728.98.plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/irazall/promotion/it/python-projects/reporting-errors/rules/snippet.py", line 10, in <module>
    post('test', { 'subject': 'World' })
  File "/home/irazall/promotion/it/virtual-env/lib/python3.7/site-packages/durable/lang.py", line 666, in post
    return get_host().post(ruleset_name, message, complete)
  File "/home/irazall/promotion/it/virtual-env/lib/python3.7/site-packages/durable/lang.py", line 661, in get_host
    _main_host.register_rulesets(ruleset_definitions)
  File "/home/irazall/promotion/it/virtual-env/lib/python3.7/site-packages/durable/engine.py", line 783, in register_rulesets
    rulesets = Ruleset.create_rulesets(self, ruleset_definitions)
  File "/home/irazall/promotion/it/virtual-env/lib/python3.7/site-packages/durable/engine.py", line 389, in create_rulesets
    branches[name] = Ruleset(name, host, definition)
  File "/home/irazall/promotion/it/virtual-env/lib/python3.7/site-packages/durable/engine.py", line 312, in __init__
    self._handle = rules.create_ruleset(name, json.dumps(ruleset_definition, ensure_ascii=False))
AttributeError: module 'rules' has no attribute 'create_ruleset'

**Comment by Irazall** [comment]
I fixed it for my part. The problem was, that I had an own module called _rules_. I renamed this module and than durable-rules could find its own module _rules_

**Comment by jruizgit** [comment]
Cool, thanks a lot for the update.

**Comment by Balakumarkct** [comment]
> I fixed it for my part. The problem was, that I had an own module called _rules_. I renamed this module and than durable-rules could find its own module _rules_

Hi how did you find where you had rules. Couldnt find in my case and still facing the same issue.
AttributeError: 'module' object has no attribute 'create_ruleset'

**Comment by Irazall** [comment]
> > I fixed it for my part. The problem was, that I had an own module called _rules_. I renamed this module and than durable-rules could find its own module _rules_
> 
> Hi how did you find where you had rules. Couldnt find in my case and still facing the same issue.
> AttributeError: 'module' object has no attribute 'create_ruleset'

Do you have a module called object? Well, I use Intellij Idea, so I just entered the class that imported that module called object and then clicked onto the import statement while pressing the CTRL-key. Afterwards I renamed that module.
